plugins:
  - jekyll-paginate

title: Taipei Forcing Club
description: Computer science and contract bridge
paginate: 10
paginate_path: /page/:num/
permalink: /:title/

defaults:
  - scope:
        path: ""
    values:
        author: jdh8
